package netscan;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;


/**
 * Classe che crea l'interfaccia grafica del programma
 * @author Andrea Del Corto-Simone Giacomelli 5IA-07
 */
public class NetscanGUI extends JFrame {
    private StylePanelMessages reportSingleHost;
    private StylePanelMessages reportRete;
    private StylePanelMessages reportPortScan;
    private ScanIpManager scanRete;
    private TPing scanSingleHost;
    private ScanServiceManager portScan;
    private static final Pattern PATTERN = Pattern.compile(
        "^(([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.){3}([01]?\\d\\d?|2[0-4]\\d|25[0-5])$");    
    /**
     * Costruttore di  NetscanGUI
     */
    public NetscanGUI() {
        initComponents();
        setTitle("Netscan");
        reportSingleHost = new StylePanelMessages(jTextPane_messaggiSingolaMacchina);
        reportRete = new StylePanelMessages(jTextPane_messaggiScanRete);
        reportPortScan = new StylePanelMessages(jTextPane_messaggiScanServizzi);
        //Set default value slider
        jLabel_nThreads.setText(Double.toString(Math.pow(2,jSlider_nThreadsRete.getValue())));
        jLabel_nThreadServizi.setText(Double.toString(Math.pow(2,jSlider_nThreadsServizzi.getValue())));
        
        jLabel_timeoutRete.setText(Integer.toString(jSlider_timeoutRete.getValue()));
        jLabel_timeoutSingleHOst.setText(Integer.toString(jSlider_timeoutSingleHost.getValue()));
        jLabel_timeoutPorte.setText(Integer.toString(jSlider_timeoutPorte.getValue()));
    }

    /**
     * Questo metodo viene chiamto insieme al costuttore e inizializza tutti i componenti
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_scanSingolaMacchina = new JPanel();
        jLabel1 = new JLabel();
        jTextField_ipSingolaMacchina = new javax.swing.JTextField();
        jLabel2 = new JLabel();
        jButton_ipUrlSingolaMacchina = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_messaggiSingolaMacchina = new javax.swing.JTextPane();
        jSlider_timeoutSingleHost = new javax.swing.JSlider();
        jLabel12 = new JLabel();
        jLabel_timeoutSingleHOst = new JLabel();
        jPanel_scanRete = new JPanel();
        jTextField_ipRete = new javax.swing.JTextField();
        jLabel3 = new JLabel();
        jButton_scanRete = new javax.swing.JButton();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jComboBox_prefisso = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_messaggiScanRete = new javax.swing.JTextPane();
        jLabel6 = new JLabel();
        jLabel_progresReteScan = new JLabel();
        jSlider_nThreadsRete = new javax.swing.JSlider();
        jLabel7 = new JLabel();
        jLabel_nThreads = new JLabel();
        jLabel11 = new JLabel();
        jSlider_timeoutRete = new javax.swing.JSlider();
        jLabel_timeoutRete = new JLabel();
        jPanel_ipScanServizzi = new JPanel();
        jLabel8 = new JLabel();
        jTextField_ipServizi = new javax.swing.JTextField();
        jButton_confermaScanServizi = new javax.swing.JButton();
        jLabel9 = new JLabel();
        jLabel_nThreadServizi = new JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane_messaggiScanServizzi = new javax.swing.JTextPane();
        jLabel10 = new JLabel();
        jSlider_nThreadsServizzi = new javax.swing.JSlider();
        jLabel_progresPortScan = new JLabel();
        jSlider_timeoutPorte = new javax.swing.JSlider();
        jLabel13 = new JLabel();
        jLabel_timeoutPorte = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("IP o URL");

        jTextField_ipSingolaMacchina.setColumns(15);
        jTextField_ipSingolaMacchina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipSingolaMacchinaActionPerformed(evt);
            }
        });

        jLabel2.setText("Report:");

        jButton_ipUrlSingolaMacchina.setText("Scan");
        jButton_ipUrlSingolaMacchina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ipUrlSingolaMacchinaActionPerformed(evt);
            }
        });

        jScrollPane2.setMaximumSize(new Dimension(355, 111));
        jScrollPane2.setViewportView(jTextPane_messaggiSingolaMacchina);

        jSlider_timeoutSingleHost.setMaximum(10000);
        jSlider_timeoutSingleHost.setMinimum(200);
        jSlider_timeoutSingleHost.setMinorTickSpacing(1);
        jSlider_timeoutSingleHost.setPaintLabels(true);
        jSlider_timeoutSingleHost.setValue(500);
        jSlider_timeoutSingleHost.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_timeoutSingleHost.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_timeoutSingleHostStateChanged(evt);
            }
        });

        jLabel12.setText("Timeout (ms)");

        javax.swing.GroupLayout jPanel_scanSingolaMacchinaLayout = new javax.swing.GroupLayout(jPanel_scanSingolaMacchina);
        jPanel_scanSingolaMacchina.setLayout(jPanel_scanSingolaMacchinaLayout);
        jPanel_scanSingolaMacchinaLayout.setHorizontalGroup(
            jPanel_scanSingolaMacchinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scanSingolaMacchinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_scanSingolaMacchinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_scanSingolaMacchinaLayout.createSequentialGroup()
                        .addGroup(jPanel_scanSingolaMacchinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(jPanel_scanSingolaMacchinaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSlider_timeoutSingleHost, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_scanSingolaMacchinaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jTextField_ipSingolaMacchina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_ipUrlSingolaMacchina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_timeoutSingleHOst)
                        .addGap(0, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_scanSingolaMacchinaLayout.setVerticalGroup(
            jPanel_scanSingolaMacchinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scanSingolaMacchinaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel_scanSingolaMacchinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_ipSingolaMacchina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_scanSingolaMacchinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jSlider_timeoutSingleHost, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_timeoutSingleHOst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ipUrlSingolaMacchina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Scan singola macchina", jPanel_scanSingolaMacchina);

        jTextField_ipRete.setColumns(15);
        jTextField_ipRete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipReteActionPerformed(evt);
            }
        });

        jLabel3.setText("Indirizzo di rete");

        jButton_scanRete.setText("Scan");
        jButton_scanRete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_scanReteActionPerformed(evt);
            }
        });

        jLabel4.setText("Prefisso di rete");

        jLabel5.setText("(bit)");

        jComboBox_prefisso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "24", "16", "8" }));
        jComboBox_prefisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_prefissoActionPerformed(evt);
            }
        });

        jScrollPane3.setMaximumSize(new Dimension(355, 111));
        jScrollPane3.setViewportView(jTextPane_messaggiScanRete);

        jLabel6.setText("Report:");

        jSlider_nThreadsRete.setMaximum(7);
        jSlider_nThreadsRete.setMinimum(1);
        jSlider_nThreadsRete.setValue(1);
        jSlider_nThreadsRete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_nThreadsRete.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_nThreadsReteStateChanged(evt);
            }
        });

        jLabel7.setText("Numero Thread");

        jLabel11.setText("Timeout (ms)");

        jSlider_timeoutRete.setMaximum(10000);
        jSlider_timeoutRete.setMinimum(200);
        jSlider_timeoutRete.setValue(500);
        jSlider_timeoutRete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_timeoutRete.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_timeoutReteStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_scanReteLayout = new javax.swing.GroupLayout(jPanel_scanRete);
        jPanel_scanRete.setLayout(jPanel_scanReteLayout);
        jPanel_scanReteLayout.setHorizontalGroup(
            jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scanReteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_scanReteLayout.createSequentialGroup()
                        .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel_scanReteLayout.createSequentialGroup()
                                .addComponent(jButton_scanRete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_progresReteScan))
                            .addGroup(jPanel_scanReteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_prefisso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel_scanReteLayout.createSequentialGroup()
                                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_scanReteLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jSlider_timeoutRete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_scanReteLayout.createSequentialGroup()
                                        .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSlider_nThreadsRete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jTextField_ipRete))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_nThreads, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_timeoutRete))))
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_scanReteLayout.setVerticalGroup(
            jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_scanReteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_ipRete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_prefisso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_nThreads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSlider_nThreadsRete, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jSlider_timeoutRete, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_timeoutRete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel_scanReteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_scanRete)
                    .addComponent(jLabel_progresReteScan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Scan rete", jPanel_scanRete);

        jLabel8.setText("Ip o URL");

        jTextField_ipServizi.setColumns(15);
        jTextField_ipServizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipServiziActionPerformed(evt);
            }
        });

        jButton_confermaScanServizi.setText("Scan");
        jButton_confermaScanServizi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confermaScanServiziActionPerformed(evt);
            }
        });

        jLabel9.setText("Numero Thread");

        jScrollPane4.setMaximumSize(new Dimension(355, 111));
        jScrollPane4.setViewportView(jTextPane_messaggiScanServizzi);

        jLabel10.setText("Report");

        jSlider_nThreadsServizzi.setMaximum(10);
        jSlider_nThreadsServizzi.setMinimum(1);
        jSlider_nThreadsServizzi.setValue(1);
        jSlider_nThreadsServizzi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_nThreadsServizzi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_nThreadsServizziStateChanged(evt);
            }
        });

        jSlider_timeoutPorte.setMaximum(10000);
        jSlider_timeoutPorte.setMinimum(200);
        jSlider_timeoutPorte.setValue(500);
        jSlider_timeoutPorte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider_timeoutPorte.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_timeoutPorteStateChanged(evt);
            }
        });

        jLabel13.setText("Timeout (ms)");

        javax.swing.GroupLayout jPanel_ipScanServizziLayout = new javax.swing.GroupLayout(jPanel_ipScanServizzi);
        jPanel_ipScanServizzi.setLayout(jPanel_ipScanServizziLayout);
        jPanel_ipScanServizziLayout.setHorizontalGroup(
            jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                        .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSlider_nThreadsServizzi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_nThreadServizi))
                            .addComponent(jLabel10)
                            .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_ipServizi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                                .addComponent(jButton_confermaScanServizi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_progresPortScan))
                            .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSlider_timeoutPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_timeoutPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_ipScanServizziLayout.setVerticalGroup(
            jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ipScanServizziLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_ipServizi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSlider_nThreadsServizzi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_nThreadServizi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_timeoutPorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSlider_timeoutPorte, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel_ipScanServizziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_confermaScanServizi)
                    .addComponent(jLabel_progresPortScan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Scan servizi di rete (TCP) attivi", jPanel_ipScanServizzi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Fa iniziare la ricerca di un host dopo aver cliccato il bottone
     * @param evt evento generato dalla pressione sul bottone
     */
    private void jButton_ipUrlSingolaMacchinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ipUrlSingolaMacchinaActionPerformed
        // TODO add your handling code here:
        findHost();
    }//GEN-LAST:event_jButton_ipUrlSingolaMacchinaActionPerformed
    /**
     * Controlla ciò che viene inserito nell'area di testo
     * @param evt evento generato dall'aver scritto nell'area di testo
     */
    private void jTextField_ipSingolaMacchinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipSingolaMacchinaActionPerformed
        // TODO add your handling code here:
        findHost();
    }//GEN-LAST:event_jTextField_ipSingolaMacchinaActionPerformed
    /**
     * Fa iniziare la ricerca dei servizzi di rete dopo aver cliccato il bottone
     * @param evt evento generato dalla pressione sul bottone
     */
    private void jButton_confermaScanServiziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confermaScanServiziActionPerformed
        // TODO add your handling code here:
        scanServizi();
    }//GEN-LAST:event_jButton_confermaScanServiziActionPerformed
    /**
     * Controlla ciò che viene inserito nell'area di testo
     * @param evt evento generato dall'aver scritto nell'area di testo
     */
    private void jTextField_ipServiziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipServiziActionPerformed
        // TODO add your handling code here:
        scanServizi();        
    }//GEN-LAST:event_jTextField_ipServiziActionPerformed
    /**
     * Modifica il numero di threads che vengono usati nello scan dei servizzi
     * @param evt evento generato dalla modifica del jSlider 
     */
    private void jSlider_nThreadsServizziStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_nThreadsServizziStateChanged
        // TODO add your handling code here:
        jLabel_nThreadServizi.setText(Double.toString(Math.pow(2,jSlider_nThreadsServizzi.getValue())));
    }//GEN-LAST:event_jSlider_nThreadsServizziStateChanged
    /**
     * Modifica il numero di threads che vengono usati nello scan della rete
     * @param evt evento generato dalla modifica del jSlider
     */
    private void jSlider_nThreadsReteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_nThreadsReteStateChanged
        jLabel_nThreads.setText(Double.toString(Math.pow(2,jSlider_nThreadsRete.getValue())));
    }//GEN-LAST:event_jSlider_nThreadsReteStateChanged
    /**
     * Fa iniziare lo scan della rete dopo aver cliccato il bottone
     * @param evt evento generato dopo aver cliccato il bottone
     */
    private void jButton_scanReteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_scanReteActionPerformed
        // TODO add your handling code here:
        scanRete();
    }//GEN-LAST:event_jButton_scanReteActionPerformed
    /**
     * Controlla ciò che viene inserito nell'area di testo
     * @param evt evento generato dall'aver scritto nell'area di testo
     */
    private void jTextField_ipReteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipReteActionPerformed
        // TODO add your handling code here:
        scanRete();
    }//GEN-LAST:event_jTextField_ipReteActionPerformed
    /**
     * Modifica il numero del tempo di timeout nello scan di rete
     * @param evt evento generato dalla modifica del jSlider
     */
    private void jSlider_timeoutReteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_timeoutReteStateChanged
        // TODO add your handling code here:
        jLabel_timeoutRete.setText(Integer.toString(jSlider_timeoutRete.getValue()));
    }//GEN-LAST:event_jSlider_timeoutReteStateChanged
    /**
     * Modifica il numero del tempo di timeout nello scan del singolo host
     * @param evt evento generato dalla modifica del jSlider
     */
    private void jSlider_timeoutSingleHostStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_timeoutSingleHostStateChanged
        // TODO add your handling code here:
        jLabel_timeoutSingleHOst.setText(Integer.toString(jSlider_timeoutSingleHost.getValue()));
    }//GEN-LAST:event_jSlider_timeoutSingleHostStateChanged
    /**
     * Modifica il numero del tempo di timeout nella ricerca dei servizzi di ret
     * @param evt evento generato dalla modifica del jSlider
     */
    private void jSlider_timeoutPorteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_timeoutPorteStateChanged
        // TODO add your handling code here:
        jLabel_timeoutPorte.setText(Integer.toString(jSlider_timeoutPorte.getValue()));
    }//GEN-LAST:event_jSlider_timeoutPorteStateChanged
    /**
     * imposta la ComboBox con dei valori al loro interno
     * @param evt evento generato dalla pressione sulla ComboBox
     */
    private void jComboBox_prefissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_prefissoActionPerformed
        // TODO add your handling code here:
        int prefix= Integer.parseInt((String) jComboBox_prefisso.getSelectedItem());
        //In base al prefisso imposto il numero di thread massimi selezionabile dall'utente
        switch(prefix){
            case 8://2^24 macchine
            jSlider_nThreadsRete.setMaximum(10);//2^10
            break;
            case 16://2^16 macchine possibili
            jSlider_nThreadsRete.setMaximum(10);//2^10
            break;
            case 24://2^8 macchine possibili
            jSlider_nThreadsRete.setMaximum(7);
            break;
        }
    }//GEN-LAST:event_jComboBox_prefissoActionPerformed
    
    /**
     * Controlla se l'indirizzo IP è valido
     * @param ip Variabile di tipo stringa che contiene l'indirizzo IP
     * @return ritorna un booleano. true se è corretto false se non lo è
     */
    public static boolean validateIp(String ip) {return PATTERN.matcher(ip).matches();} 
    /**
     * Metodo che gestisce lo scan dei servizzi di rete
     */
    private void scanServizi(){
      String ip_url=jTextField_ipServizi.getText();
      int nThread = (int)Double.parseDouble(jLabel_nThreadServizi.getText());
      int timeout=jSlider_timeoutPorte.getValue();
      if(!ip_url.isEmpty()){//Se è stato inserito qualcosa
          
          if(portScan!=null && portScan.isScanning()){//Scansione in corso?
            if (JOptionPane.showConfirmDialog(this, "Si desidera veramente interrompere la scansione?", "WARNING",
              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
              // yes option
              //jButton_confermaScanServizi.setText("Scan");  
              portScan.interrupt();
              portScan=null;
              reportPortScan.panel=null;
              reportPortScan = new StylePanelMessages(jTextPane_messaggiScanServizzi);
              portScan=null;
            } 
          }
          else{
            //jButton_confermaScanServizi.setText("Stop Scan");
            portScan = new ScanServiceManager(ip_url,nThread,reportPortScan,jLabel_progresPortScan,timeout);
            portScan.startScan();      
          }          
      }
      else{
        JOptionPane.showMessageDialog(this, "Inserisci un ip o un URL.","Attenzione", JOptionPane.ERROR_MESSAGE);        
      }        
        
    }
    /**
     * Metodo che gestisce lo scan della rete
     */
    private void scanRete(){
        String ip= jTextField_ipRete.getText();
        int prefix= Integer.parseInt((String) jComboBox_prefisso.getSelectedItem());
        int nThread = (int)Double.parseDouble(jLabel_nThreads.getText());
        int timeout=jSlider_timeoutRete.getValue(); 
        if(validateIp(ip)){          
          if(scanRete!=null && scanRete.isScanning()){//Scansione in corso?
            if (JOptionPane.showConfirmDialog(this, "Si desidera veramente interrompere la scansione?", "WARNING",
              JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
              // yes option
              //jButton_scanRete.setText("Scan");  
              scanRete.interrupt();
              scanRete=null;
              reportRete.panel=null;
              reportRete = new StylePanelMessages(jTextPane_messaggiScanRete);
              scanRete=null;
            } 
          }
          else{
            //jButton_scanRete.setText("Stop Scan");
            scanRete = new ScanIpManager(prefix,ip,nThread,reportRete,jLabel_progresReteScan,timeout);
            scanRete.startScan();          
          }
        }
        else{
          JOptionPane.showMessageDialog(this, "Inserisci un IP valido.","Attenzione", JOptionPane.ERROR_MESSAGE);        
        }
    
    }
    /**
     * Metodo che gestisce lo scan del singolo host
     */
    private void findHost(){
        String ip_url=jTextField_ipSingolaMacchina.getText();
        if(!ip_url.isEmpty()){//Se è stato inserito qualcosa dentro il ping
          //TPing  test= new TPing(ip_url,reportSingolaMacchina);
          //test.start();
          int timeout=jSlider_timeoutSingleHost.getValue();  
          scanSingleHost=new TPing(ip_url,reportSingleHost,timeout);
          scanSingleHost.start();
        }
        else{
          JOptionPane.showMessageDialog(this, "Inserisci un ip o un URL.","Attenzione", JOptionPane.ERROR_MESSAGE);        
        }      
    }
    /**
     * Metodo che viene richiamto quando parte il programma
     * @param args argomenti dati da linea di comando
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetscanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetscanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetscanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetscanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetscanGUI().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_confermaScanServizi;
    private javax.swing.JButton jButton_ipUrlSingolaMacchina;
    private javax.swing.JButton jButton_scanRete;
    private javax.swing.JComboBox jComboBox_prefisso;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JLabel jLabel_nThreadServizi;
    private JLabel jLabel_nThreads;
    private JLabel jLabel_progresPortScan;
    private JLabel jLabel_progresReteScan;
    private JLabel jLabel_timeoutPorte;
    private JLabel jLabel_timeoutRete;
    private JLabel jLabel_timeoutSingleHOst;
    private JPanel jPanel_ipScanServizzi;
    private JPanel jPanel_scanRete;
    private JPanel jPanel_scanSingolaMacchina;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider_nThreadsRete;
    private javax.swing.JSlider jSlider_nThreadsServizzi;
    private javax.swing.JSlider jSlider_timeoutPorte;
    private javax.swing.JSlider jSlider_timeoutRete;
    private javax.swing.JSlider jSlider_timeoutSingleHost;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_ipRete;
    private javax.swing.JTextField jTextField_ipServizi;
    private javax.swing.JTextField jTextField_ipSingolaMacchina;
    private javax.swing.JTextPane jTextPane_messaggiScanRete;
    private javax.swing.JTextPane jTextPane_messaggiScanServizzi;
    private javax.swing.JTextPane jTextPane_messaggiSingolaMacchina;
    // End of variables declaration//GEN-END:variables
}
